version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:15.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master
      POSTGRES_DB: simple_db
    ports:
      - "5432:5432"
    volumes:
      - app_db:/var/lib/postgresql/data

  file-storage:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: KiaRfgEmF7
    volumes:
      - file-storage-data:/data

  create-buckets:
    image: minio/mc
    depends_on:
      - file-storage
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://file-storage:9000 root KiaRfgEmF7;
      /usr/bin/mc mb myminio/images;
      exit 0;
      "

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass yeYsTJ,RtoXF4GI
    volumes:
      - app-redis:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs_db
    volumes:
      - app-mongodb:/data/db
      - app-mongo-config:/data/configdb

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - file-storage
      - redis
      - mongodb

volumes:
  app_db:
  file-storage-data:
  app-redis:
  app-mongodb:
  app-mongo-config: