version: "2"
services:
  postgres:
    container_name: postgres
    image: postgres:15.5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "master"
      POSTGRES_DB: "simple_db"
    ports:
      - "5432:5432"
    volumes:
      - app_db:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  app_db: